<?php

declare(strict_types=1);

namespace Fschmtt\Keycloak\Enum;

enum RequiredAction: string implements Enum
{
    case UPDATE_PASSWORD = 'UPDATE_PASSWORD';
    case VERIFY_EMAIL = 'VERIFY_EMAIL';
    case CONFIGURE_OTP = 'CONFIGURE_OTP';
    case UPDATE_PROFILE = 'UPDATE_PROFILE';
    case UPDATE_USER_LOCALE = 'UPDATE_USER_LOCALE';
    case VERIFY_PROFILE = 'VERIFY_PROFILE';
    case DELETE_CREDENTIAL = 'DELETE_CREDENTIAL';
    case WEBAUTHN_REGISTER = 'WEBAUTHN_REGISTER';
    case WEBAUTHN_REGISTER_PASSWORDLESS = 'WEBAUTHN_REGISTER_PASSWORDLESS';
    case TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
    case DELETE_ACCOUNT = 'DELETE_ACCOUNT';
}
