<?php

declare(strict_types=1);

namespace Fschmtt\Keycloak\Representation;

class User extends Representation
{
    protected ?array $access;

    protected ?array $attributes;

    /**
     * @var UserConsent[]|null
     */
    protected ?array $clientConsents;

    protected ?array $clientRoles;

    protected ?int $createdTimestamp;

    /**
     * @var Credential[]|null
     */
    protected ?array $credentials;

    protected ?array $disableableCredentialTypes;

    protected ?string $email;

    protected ?bool $emailVerified;

    protected ?bool $enabled;

    /**
     * @var FederatedIdentity[]|null
     */
    protected ?array $federatedIdentities;

    protected ?string $federationLink;

    protected ?string $firstName;

    protected ?array $groups;

    protected ?string $id;

    protected ?string $lastName;

    protected ?int $notBefore;

    protected ?string $origin;

    protected $realmRoles;

    protected ?array $requiredActions;

    protected ?string $self;

    protected ?string $serviceAccountClientId;

    protected ?string $username;

    public static function from(array $properties): static
    {
        return parent::from($properties); // TODO: Change the autogenerated stub
    }
}
